import type { JSX } from "react"
import { Montserrat } from "next/font/google"

import "@/app/globals.css"
import NextAuthProvider from "@/components/layout/NextAuthProvider"

const montserrat = Montserrat({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}): Promise<JSX.Element> {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}
