import type { JSX } from "react"
import { Montserrat } from "next/font/google"
import Logo from "@/../public/logo/logo.png"
import "@/app/globals.css"
import NextAuthProvider from "@/components/layout/NextAuthProvider"
import Image from "next/image"
import "@/styles/typography.css"

const montserrat = Montserrat({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}): Promise<JSX.Element> {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <NextAuthProvider>
          <div className="h-screen grid-cols-2 overflow-y-auto md:grid">
            {/* Left Column */}
            <div className="flex items-center justify-center p-5 bg-Primary-700">
              <Image src={Logo} alt="Logo" width={500} height={400} />
            </div>

            {/* Right Column */}
            <div className="flex flex-col items-center justify-center max-w-[450px] mx-auto px-5 space-y-3 md:space-y-4 py-5">
              {children}
            </div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
