export interface translationsTypes {
  [x: string]: string
  delete: string
  addNewStore: string
  allowMultiLang: string
  english: string
  french: string
  storeName: string
  enterStoreName: string
  category: string
  selectCategory: string
  storeLocation: string
  enterStoreLocation: string
  storeType: string
  selectStoreType: string
  storeMapLocation: string
  enterMapLocation: string
  subscription: string
  premium: string
  freemium: string
  time: string
  from: string
  to: string
  storeContact: string
  mobileNumber: string
  enterStoreNumber: string
  email: string
  enterStoreEmail: string
  mapsPin: string
  enterGoogleMapsLocation: string
  facebook: string
  enterFacebookUrl: string
  instagram: string
  enterInstagramUrl: string
  website: string
  enterWebsiteUrl: string
  availableProducts: string
  selectAvailableIngredients: string
  searchForIngredients: string
  selectAvailableCategories: string
  searchAvailableCategories: string
  add: string
  availableIngredientsAndCategories: string
  type: string
  availabilityStatus: string
  active: string
  inactive: string
  displayStatus: string
  aboutTheShop: string
  aboutUs: string
  uploadImages: string
  selectImagesForYourStore: string
  cancel: string
  save: string
  breakfast: string
  dinner: string
  dairy: string
  physical: string
  online: string
  ingredient: string

  required: string
  mustbeatleast2characters: string
  pleaseselectacategory: string
  pleaseselectaStoreType: string
  invalidmobilenumbereg0712345678or94712345678: string
  pleaseenteravalidemail: string
  invalidurlformat: string
  atleastoneingredientcategorymustbeadded: string
  formSubmittedSuccessfully: string
}

export const defaultTranslations: translationsTypes = {
  delete: "",
  addNewStore: "",
  allowMultiLang: "",
  english: "",
  french: "",
  storeName: "",
  enterStoreName: "",
  category: "",
  selectCategory: "",
  storeLocation: "",
  enterStoreLocation: "",
  storeType: "",
  selectStoreType: "",
  storeMapLocation: "",
  enterMapLocation: "",
  subscription: "",
  premium: "",
  freemium: "",
  time: "",
  from: "",
  to: "",
  storeContact: "",
  mobileNumber: "",
  enterStoreNumber: "",
  email: "",
  enterStoreEmail: "",
  mapsPin: "",
  enterGoogleMapsLocation: "",
  facebook: "",
  enterFacebookUrl: "",
  instagram: "",
  enterInstagramUrl: "",
  website: "",
  enterWebsiteUrl: "",
  availableProducts: "",
  selectAvailableIngredients: "",
  searchForIngredients: "",
  selectAvailableCategories: "",
  searchAvailableCategories: "",
  add: "",
  availableIngredientsAndCategories: "",
  type: "",
  availabilityStatus: "",
  active: "",
  inactive: "",
  displayStatus: "",
  aboutTheShop: "",
  aboutUs: "",
  uploadImages: "",
  selectImagesForYourStore: "",
  cancel: "",
  save: "",
  breakfast: "",
  dinner: "",
  dairy: "",
  physical: "",
  online: "",
  ingredient: "",

  required: "",
  mustbeatleast2characters: "",
  pleaseselectacategory: "",
  pleaseselectaStoreType: "",
  invalidmobilenumbereg0712345678or94712345678: "",
  pleaseenteravalidemail: "",
  invalidurlformat: "",
  atleastoneingredientcategorymustbeadded: "",
  formSubmittedSuccessfully: ""
}
